// Code generated by hertz generator.

package avatar_serv

import (
	"context"

	"douyin/avatar/serv_template_open/biz/implements"
	"douyin/avatar/serv_template_open/biz/model/avatar_serv"
	"douyin/avatar/serv_template_open/biz/util"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/pkg/errors"
)

// OnBoarding .
// @router /onboarding [POST]
func OnBoarding(ctx context.Context, c *app.RequestContext) {
	var err error
	var req avatar_serv.OnBoardingRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		util.SendErrResp(ctx, c, -1, err)
		return
	}

	implements.OnBoarding(ctx, c, &req)
}

// ChatStream .
// @router /chat_stream [POST]
func ChatStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req avatar_serv.ChatStreamRequest
	err = c.BindAndValidate(&req)

	if err != nil {
		util.SendErrResp(ctx, c, -1, err)
		return
	}

	implements.ChatStream(ctx, c, &req)
}

// Chat .
// @router /chat [POST]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req avatar_serv.ChatRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		util.SendErrResp(ctx, c, -1, err)
		return
	}

	resp := implements.Chat(ctx, c, &req)
	if resp.BaseResp != nil && resp.BaseResp.StatusCode != 0 {
		util.SendErrResp(ctx, c, int(resp.BaseResp.GetStatusCode()), errors.New(resp.BaseResp.GetStatusMessage()))
		return
	}
	util.SendSucResp(ctx, c, resp)
}
