// Code generated by thriftgo (0.3.17). DO NOT EDIT.

package schema

import (
	"database/sql"
	"database/sql/driver"
	"douyin/avatar/serv_template_open/biz/model/base"
	"douyin/avatar/serv_template_open/biz/model/common"
	"fmt"
)

type MemoryType int64

const (
	// 篇章型记忆，append only
	MemoryType_Episodic MemoryType = 1
	// 语义型记忆，支持更新，每次总结会带上所有之前的语义总结
	MemoryType_Semantic MemoryType = 2
)

func (p MemoryType) String() string {
	switch p {
	case MemoryType_Episodic:
		return "Episodic"
	case MemoryType_Semantic:
		return "Semantic"
	}
	return "<UNSET>"
}

func MemoryTypeFromString(s string) (MemoryType, error) {
	switch s {
	case "Episodic":
		return MemoryType_Episodic, nil
	case "Semantic":
		return MemoryType_Semantic, nil
	}
	return MemoryType(0), fmt.Errorf("not a valid MemoryType string")
}

func MemoryTypePtr(v MemoryType) *MemoryType { return &v }
func (p *MemoryType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = MemoryType(result.Int64)
	return
}

func (p *MemoryType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type QueryOperator int64

const (
	QueryOperator_IN     QueryOperator = 1
	QueryOperator_NOT_IN QueryOperator = 2
)

func (p QueryOperator) String() string {
	switch p {
	case QueryOperator_IN:
		return "IN"
	case QueryOperator_NOT_IN:
		return "NOT_IN"
	}
	return "<UNSET>"
}

func QueryOperatorFromString(s string) (QueryOperator, error) {
	switch s {
	case "IN":
		return QueryOperator_IN, nil
	case "NOT_IN":
		return QueryOperator_NOT_IN, nil
	}
	return QueryOperator(0), fmt.Errorf("not a valid QueryOperator string")
}

func QueryOperatorPtr(v QueryOperator) *QueryOperator { return &v }
func (p *QueryOperator) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = QueryOperator(result.Int64)
	return
}

func (p *QueryOperator) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AvatarRequestInfo struct {
	// 所有 Id 均只能使用 英文字符、数字、下划线、中划线
	BizID string `thrift:"biz_id,1,required" form:"biz_id,required" json:"biz_id,required" query:"biz_id,required"`
	// 业务流量标识信息
	TrafficSource *common.TrafficSource `thrift:"traffic_source,2,optional" form:"traffic_source" json:"traffic_source,omitempty" query:"traffic_source"`
	//  用户在分身场景下open_id
	OpenID string `thrift:"open_id,3,required" form:"open_id,required" json:"open_id,required" query:"open_id,required"`
	//  分身容器app_id
	AvatarAppID string `thrift:"avatar_app_id,4,required" form:"avatar_app_id,required" json:"avatar_app_id,required" query:"avatar_app_id,required"`
	//  原子能力租户id，用于原子能力数据隔离隔离，可用于测试或评测场景，若无特殊诉求使用 default 或留空
	TenantID *string `thrift:"tenant_id,5,optional" form:"tenant_id" json:"tenant_id,omitempty" query:"tenant_id"`
	// 消息发送者的应用类别，主要用于记忆模块策略配置
	ProviderID *string `thrift:"provider_id,6,optional" form:"provider_id" json:"provider_id,omitempty" query:"provider_id"`
}

func NewAvatarRequestInfo() *AvatarRequestInfo {
	return &AvatarRequestInfo{}
}

func (p *AvatarRequestInfo) InitDefault() {
}

func (p *AvatarRequestInfo) GetBizID() (v string) {
	return p.BizID
}

func (p *AvatarRequestInfo) GetOpenID() (v string) {
	return p.OpenID
}

func (p *AvatarRequestInfo) GetAvatarAppID() (v string) {
	return p.AvatarAppID
}

var AvatarRequestInfo_TenantID_DEFAULT string

func (p *AvatarRequestInfo) GetTenantID() (v string) {
	if !p.IsSetTenantID() {
		return AvatarRequestInfo_TenantID_DEFAULT
	}
	return *p.TenantID
}

var AvatarRequestInfo_ProviderID_DEFAULT string

func (p *AvatarRequestInfo) GetProviderID() (v string) {
	if !p.IsSetProviderID() {
		return AvatarRequestInfo_ProviderID_DEFAULT
	}
	return *p.ProviderID
}

func (p *AvatarRequestInfo) IsSetTrafficSource() bool {
	return p.TrafficSource != nil
}

func (p *AvatarRequestInfo) IsSetTenantID() bool {
	return p.TenantID != nil
}

func (p *AvatarRequestInfo) IsSetProviderID() bool {
	return p.ProviderID != nil
}

func (p *AvatarRequestInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AvatarRequestInfo(%+v)", *p)
}

var CommonContext_AvatarRequestInfo_DEFAULT *AvatarRequestInfo

type ContentVectorModelNameCondition struct {
	Operator                 QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	ContentVectorMomdelNames []string      `thrift:"content_vector_momdel_names,2" form:"content_vector_momdel_names" json:"content_vector_momdel_names" query:"content_vector_momdel_names"`
}

func NewContentVectorModelNameCondition() *ContentVectorModelNameCondition {
	return &ContentVectorModelNameCondition{}
}

func (p *ContentVectorModelNameCondition) InitDefault() {
}

func (p *ContentVectorModelNameCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *ContentVectorModelNameCondition) GetContentVectorMomdelNames() (v []string) {
	return p.ContentVectorMomdelNames
}

func (p *ContentVectorModelNameCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ContentVectorModelNameCondition(%+v)", *p)
}

type GroupCondition struct {
	Operator QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	Groups   []string      `thrift:"groups,2" form:"groups" json:"groups" query:"groups"`
}

func NewGroupCondition() *GroupCondition {
	return &GroupCondition{}
}

func (p *GroupCondition) InitDefault() {
}

func (p *GroupCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *GroupCondition) GetGroups() (v []string) {
	return p.Groups
}

func (p *GroupCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GroupCondition(%+v)", *p)
}

type MemoryIdCondition struct {
	Operator  QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	MemoryIds []string      `thrift:"memory_ids,2" form:"memory_ids" json:"memory_ids" query:"memory_ids"`
}

func NewMemoryIdCondition() *MemoryIdCondition {
	return &MemoryIdCondition{}
}

func (p *MemoryIdCondition) InitDefault() {
}

func (p *MemoryIdCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *MemoryIdCondition) GetMemoryIds() (v []string) {
	return p.MemoryIds
}

func (p *MemoryIdCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryIdCondition(%+v)", *p)
}

type MemoryTypeCondition struct {
	Operator   QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	MemoryType MemoryType    `thrift:"memory_type,2" form:"memory_type" json:"memory_type" query:"memory_type"`
}

func NewMemoryTypeCondition() *MemoryTypeCondition {
	return &MemoryTypeCondition{}
}

func (p *MemoryTypeCondition) InitDefault() {
}

func (p *MemoryTypeCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *MemoryTypeCondition) GetMemoryType() (v MemoryType) {
	return p.MemoryType
}

func (p *MemoryTypeCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryTypeCondition(%+v)", *p)
}

type SubGroupCondition struct {
	Operator  QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	SubGroups []string      `thrift:"sub_groups,2" form:"sub_groups" json:"sub_groups" query:"sub_groups"`
}

func NewSubGroupCondition() *SubGroupCondition {
	return &SubGroupCondition{}
}

func (p *SubGroupCondition) InitDefault() {
}

func (p *SubGroupCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *SubGroupCondition) GetSubGroups() (v []string) {
	return p.SubGroups
}

func (p *SubGroupCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("SubGroupCondition(%+v)", *p)
}

type CreateTimeCondition struct {
	Operator       QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	StartTimeMilli int64         `thrift:"start_time_milli,2" form:"start_time_milli" json:"start_time_milli" query:"start_time_milli"`
	EndTimeMilli   int64         `thrift:"end_time_milli,3" form:"end_time_milli" json:"end_time_milli" query:"end_time_milli"`
}

func NewCreateTimeCondition() *CreateTimeCondition {
	return &CreateTimeCondition{}
}

func (p *CreateTimeCondition) InitDefault() {
}

func (p *CreateTimeCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *CreateTimeCondition) GetStartTimeMilli() (v int64) {
	return p.StartTimeMilli
}

func (p *CreateTimeCondition) GetEndTimeMilli() (v int64) {
	return p.EndTimeMilli
}

func (p *CreateTimeCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CreateTimeCondition(%+v)", *p)
}

type UpdateTimeCondition struct {
	Operator       QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	StartTimeMilli int64         `thrift:"start_time_milli,2" form:"start_time_milli" json:"start_time_milli" query:"start_time_milli"`
	EndTimeMilli   int64         `thrift:"end_time_milli,3" form:"end_time_milli" json:"end_time_milli" query:"end_time_milli"`
}

func NewUpdateTimeCondition() *UpdateTimeCondition {
	return &UpdateTimeCondition{}
}

func (p *UpdateTimeCondition) InitDefault() {
}

func (p *UpdateTimeCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *UpdateTimeCondition) GetStartTimeMilli() (v int64) {
	return p.StartTimeMilli
}

func (p *UpdateTimeCondition) GetEndTimeMilli() (v int64) {
	return p.EndTimeMilli
}

func (p *UpdateTimeCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateTimeCondition(%+v)", *p)
}

type MemoryDateCondition struct {
	Operator       QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	StartTimeMilli int64         `thrift:"start_time_milli,2" form:"start_time_milli" json:"start_time_milli" query:"start_time_milli"`
	EndTimeMilli   int64         `thrift:"end_time_milli,3" form:"end_time_milli" json:"end_time_milli" query:"end_time_milli"`
}

func NewMemoryDateCondition() *MemoryDateCondition {
	return &MemoryDateCondition{}
}

func (p *MemoryDateCondition) InitDefault() {
}

func (p *MemoryDateCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *MemoryDateCondition) GetStartTimeMilli() (v int64) {
	return p.StartTimeMilli
}

func (p *MemoryDateCondition) GetEndTimeMilli() (v int64) {
	return p.EndTimeMilli
}

func (p *MemoryDateCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryDateCondition(%+v)", *p)
}

type MemoryNameCondition struct {
	Operator    QueryOperator `thrift:"operator,1" form:"operator" json:"operator" query:"operator"`
	MemoryNames []string      `thrift:"memory_names,2" form:"memory_names" json:"memory_names" query:"memory_names"`
}

func NewMemoryNameCondition() *MemoryNameCondition {
	return &MemoryNameCondition{}
}

func (p *MemoryNameCondition) InitDefault() {
}

func (p *MemoryNameCondition) GetOperator() (v QueryOperator) {
	return p.Operator
}

func (p *MemoryNameCondition) GetMemoryNames() (v []string) {
	return p.MemoryNames
}

func (p *MemoryNameCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryNameCondition(%+v)", *p)
}

type QueryCondition struct {
	// 各筛选条件均支持in与not_in选项，分别对应operator 1与2
	ContentVectorModelNameCondition *ContentVectorModelNameCondition `thrift:"content_vector_model_name_condition,1,optional" form:"content_vector_model_name_condition" json:"content_vector_model_name_condition,omitempty" query:"content_vector_model_name_condition"`
	// 组筛选
	GroupCondition *GroupCondition `thrift:"group_condition,2,optional" form:"group_condition" json:"group_condition,omitempty" query:"group_condition"`
	// 记忆ID筛选
	MemoryIDCondition *MemoryIdCondition `thrift:"memory_id_condition,3,optional" form:"memory_id_condition" json:"memory_id_condition,omitempty" query:"memory_id_condition"`
	// 记忆类型筛选：1为episodic，2为semantic
	MemoryTypeCondition *MemoryTypeCondition `thrift:"memory_type_condition,4,optional" form:"memory_type_condition" json:"memory_type_condition,omitempty" query:"memory_type_condition"`
	// 记忆名筛选
	MemoryNameCondition *MemoryNameCondition `thrift:"memory_name_condition,5,optional" form:"memory_name_condition" json:"memory_name_condition,omitempty" query:"memory_name_condition"`
	// 副组筛选
	SubGroupCondition *SubGroupCondition `thrift:"sub_group_condition,6,optional" form:"sub_group_condition" json:"sub_group_condition,omitempty" query:"sub_group_condition"`
	// 记忆创建时间筛选：unix milli时间戳，起始时间与终止时间为闭区间
	CreateTimeCondition *CreateTimeCondition `thrift:"create_time_condition,7,optional" form:"create_time_condition" json:"create_time_condition,omitempty" query:"create_time_condition"`
	// 记忆更新时间筛选：unix milli时间戳，起始时间与终止时间为闭区间
	UpdateTimeCondition *UpdateTimeCondition `thrift:"update_time_condition,8,optional" form:"update_time_condition" json:"update_time_condition,omitempty" query:"update_time_condition"`
	// 记忆时间筛选：unix sec时间戳，起始时间与终止时间为闭区间
	MemoryDateCondition *MemoryDateCondition `thrift:"memory_date_condition,9,optional" form:"memory_date_condition" json:"memory_date_condition,omitempty" query:"memory_date_condition"`
}

func NewQueryCondition() *QueryCondition {
	return &QueryCondition{}
}

func (p *QueryCondition) InitDefault() {
}

var QueryCondition_ContentVectorModelNameCondition_DEFAULT *ContentVectorModelNameCondition

func (p *QueryCondition) GetContentVectorModelNameCondition() (v *ContentVectorModelNameCondition) {
	if !p.IsSetContentVectorModelNameCondition() {
		return QueryCondition_ContentVectorModelNameCondition_DEFAULT
	}
	return p.ContentVectorModelNameCondition
}

var QueryCondition_GroupCondition_DEFAULT *GroupCondition

func (p *QueryCondition) GetGroupCondition() (v *GroupCondition) {
	if !p.IsSetGroupCondition() {
		return QueryCondition_GroupCondition_DEFAULT
	}
	return p.GroupCondition
}

var QueryCondition_MemoryIDCondition_DEFAULT *MemoryIdCondition

func (p *QueryCondition) GetMemoryIDCondition() (v *MemoryIdCondition) {
	if !p.IsSetMemoryIDCondition() {
		return QueryCondition_MemoryIDCondition_DEFAULT
	}
	return p.MemoryIDCondition
}

var QueryCondition_MemoryTypeCondition_DEFAULT *MemoryTypeCondition

func (p *QueryCondition) GetMemoryTypeCondition() (v *MemoryTypeCondition) {
	if !p.IsSetMemoryTypeCondition() {
		return QueryCondition_MemoryTypeCondition_DEFAULT
	}
	return p.MemoryTypeCondition
}

var QueryCondition_MemoryNameCondition_DEFAULT *MemoryNameCondition

func (p *QueryCondition) GetMemoryNameCondition() (v *MemoryNameCondition) {
	if !p.IsSetMemoryNameCondition() {
		return QueryCondition_MemoryNameCondition_DEFAULT
	}
	return p.MemoryNameCondition
}

var QueryCondition_SubGroupCondition_DEFAULT *SubGroupCondition

func (p *QueryCondition) GetSubGroupCondition() (v *SubGroupCondition) {
	if !p.IsSetSubGroupCondition() {
		return QueryCondition_SubGroupCondition_DEFAULT
	}
	return p.SubGroupCondition
}

var QueryCondition_CreateTimeCondition_DEFAULT *CreateTimeCondition

func (p *QueryCondition) GetCreateTimeCondition() (v *CreateTimeCondition) {
	if !p.IsSetCreateTimeCondition() {
		return QueryCondition_CreateTimeCondition_DEFAULT
	}
	return p.CreateTimeCondition
}

var QueryCondition_UpdateTimeCondition_DEFAULT *UpdateTimeCondition

func (p *QueryCondition) GetUpdateTimeCondition() (v *UpdateTimeCondition) {
	if !p.IsSetUpdateTimeCondition() {
		return QueryCondition_UpdateTimeCondition_DEFAULT
	}
	return p.UpdateTimeCondition
}

var QueryCondition_MemoryDateCondition_DEFAULT *MemoryDateCondition

func (p *QueryCondition) GetMemoryDateCondition() (v *MemoryDateCondition) {
	if !p.IsSetMemoryDateCondition() {
		return QueryCondition_MemoryDateCondition_DEFAULT
	}
	return p.MemoryDateCondition
}

func (p *QueryCondition) IsSetContentVectorModelNameCondition() bool {
	return p.ContentVectorModelNameCondition != nil
}

func (p *QueryCondition) IsSetGroupCondition() bool {
	return p.GroupCondition != nil
}

func (p *QueryCondition) IsSetMemoryIDCondition() bool {
	return p.MemoryIDCondition != nil
}

func (p *QueryCondition) IsSetMemoryTypeCondition() bool {
	return p.MemoryTypeCondition != nil
}

func (p *QueryCondition) IsSetMemoryNameCondition() bool {
	return p.MemoryNameCondition != nil
}

func (p *QueryCondition) IsSetSubGroupCondition() bool {
	return p.SubGroupCondition != nil
}

func (p *QueryCondition) IsSetCreateTimeCondition() bool {
	return p.CreateTimeCondition != nil
}

func (p *QueryCondition) IsSetUpdateTimeCondition() bool {
	return p.UpdateTimeCondition != nil
}

func (p *QueryCondition) IsSetMemoryDateCondition() bool {
	return p.MemoryDateCondition != nil
}

func (p *QueryCondition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("QueryCondition(%+v)", *p)
}

type MemoryDsl struct {
	// 筛选条件为选填，不需要的参数（如memory_type）可以删掉该部分
	QueryConditions *QueryCondition `thrift:"query_conditions,1" form:"query_conditions" json:"query_conditions" query:"query_conditions"`
	// 模糊匹配：向量查询，开启后会将query进行词嵌入后作为匹配条件
	EnableVectorSearch bool `thrift:"enable_vector_search,2" form:"enable_vector_search" json:"enable_vector_search" query:"enable_vector_search"`
	// 模糊匹配：关键字查询，开启后会将query作为匹配条件
	EnableKeywordSearch bool `thrift:"enable_keyword_search,3" form:"enable_keyword_search" json:"enable_keyword_search" query:"enable_keyword_search"`
}

func NewMemoryDsl() *MemoryDsl {
	return &MemoryDsl{}
}

func (p *MemoryDsl) InitDefault() {
}

var MemoryDsl_QueryConditions_DEFAULT *QueryCondition

func (p *MemoryDsl) GetQueryConditions() (v *QueryCondition) {
	if !p.IsSetQueryConditions() {
		return MemoryDsl_QueryConditions_DEFAULT
	}
	return p.QueryConditions
}

func (p *MemoryDsl) GetEnableVectorSearch() (v bool) {
	return p.EnableVectorSearch
}

func (p *MemoryDsl) GetEnableKeywordSearch() (v bool) {
	return p.EnableKeywordSearch
}

func (p *MemoryDsl) IsSetQueryConditions() bool {
	return p.QueryConditions != nil
}

func (p *MemoryDsl) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryDsl(%+v)", *p)
}

type MemoryRecallParams struct {
	Dsl   *MemoryDsl `thrift:"dsl,1,optional" form:"dsl" json:"dsl,omitempty" query:"dsl"`
	Query *string    `thrift:"query,2,optional" form:"query" json:"query,omitempty" query:"query"`
	Limit *int32     `thrift:"limit,3,optional" form:"limit" json:"limit,omitempty" query:"limit"`
}

func NewMemoryRecallParams() *MemoryRecallParams {
	return &MemoryRecallParams{}
}

func (p *MemoryRecallParams) InitDefault() {
}

var MemoryRecallParams_Dsl_DEFAULT *MemoryDsl

func (p *MemoryRecallParams) GetDsl() (v *MemoryDsl) {
	if !p.IsSetDsl() {
		return MemoryRecallParams_Dsl_DEFAULT
	}
	return p.Dsl
}

var MemoryRecallParams_Query_DEFAULT string

func (p *MemoryRecallParams) GetQuery() (v string) {
	if !p.IsSetQuery() {
		return MemoryRecallParams_Query_DEFAULT
	}
	return *p.Query
}

var MemoryRecallParams_Limit_DEFAULT int32

func (p *MemoryRecallParams) GetLimit() (v int32) {
	if !p.IsSetLimit() {
		return MemoryRecallParams_Limit_DEFAULT
	}
	return *p.Limit
}

func (p *MemoryRecallParams) IsSetDsl() bool {
	return p.Dsl != nil
}

func (p *MemoryRecallParams) IsSetQuery() bool {
	return p.Query != nil
}

func (p *MemoryRecallParams) IsSetLimit() bool {
	return p.Limit != nil
}

func (p *MemoryRecallParams) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryRecallParams(%+v)", *p)
}

type MemoryRecallRequest struct {
	Params        *MemoryRecallParams `thrift:"params,1" form:"params" json:"params" query:"params"`
	RequestInfo   *AvatarRequestInfo      `thrift:"request_info,200" form:"request_info" json:"request_info" query:"request_info"`
}

func NewMemoryRecallRequest() *MemoryRecallRequest {
	return &MemoryRecallRequest{}
}

func (p *MemoryRecallRequest) InitDefault() {
}

var MemoryRecallRequest_Params_DEFAULT *MemoryRecallParams

func (p *MemoryRecallRequest) GetParams() (v *MemoryRecallParams) {
	if !p.IsSetParams() {
		return MemoryRecallRequest_Params_DEFAULT
	}
	return p.Params
}

var MemoryRecallRequest_RequestInfo_DEFAULT *AvatarRequestInfo

func (p *MemoryRecallRequest) GetRequestInfo() (v *AvatarRequestInfo) {
	if !p.IsSetRequestInfo() {
		return MemoryRecallRequest_RequestInfo_DEFAULT
	}
	return p.RequestInfo
}

var MemoryRecallRequest_Base_DEFAULT *base.Base


func (p *MemoryRecallRequest) IsSetParams() bool {
	return p.Params != nil
}

func (p *MemoryRecallRequest) IsSetRequestInfo() bool {
	return p.RequestInfo != nil
}


func (p *MemoryRecallRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryRecallRequest(%+v)", *p)
}

type Memory struct {
	MemoryID               string            `thrift:"memory_id,1" form:"memory_id" json:"memory_id" query:"memory_id"`
	UserID                 *string           `thrift:"user_id,2,optional" form:"user_id" json:"user_id,omitempty" query:"user_id"`
	AvatarID               *string           `thrift:"avatar_id,3,optional" form:"avatar_id" json:"avatar_id,omitempty" query:"avatar_id"`
	MemoryType             MemoryType        `thrift:"memory_type,4" form:"memory_type" json:"memory_type" query:"memory_type"`
	MemoryName             string            `thrift:"memory_name,5" form:"memory_name" json:"memory_name" query:"memory_name"`
	Group                  string            `thrift:"group,6" form:"group" json:"group" query:"group"`
	SubGroup               string            `thrift:"sub_group,7" form:"sub_group" json:"sub_group" query:"sub_group"`
	Content                string            `thrift:"content,8" form:"content" json:"content" query:"content"`
	ContentVector          []float64         `thrift:"content_vector,9,optional" form:"content_vector" json:"content_vector,omitempty" query:"content_vector"`
	CreatedAtUnixMilli     int64             `thrift:"created_at_unix_milli,10" form:"created_at_unix_milli" json:"created_at_unix_milli" query:"created_at_unix_milli"`
	LastUpdatedAtUnixMilli int64             `thrift:"last_updated_at_unix_milli,11" form:"last_updated_at_unix_milli" json:"last_updated_at_unix_milli" query:"last_updated_at_unix_milli"`
	MemoryDateAtUnixSec    int64             `thrift:"memory_date_at_unix_sec,12" form:"memory_date_at_unix_sec" json:"memory_date_at_unix_sec" query:"memory_date_at_unix_sec"`
	Ext                    map[string]string `thrift:"ext,13" form:"ext" json:"ext" query:"ext"`
}

func NewMemory() *Memory {
	return &Memory{}
}

func (p *Memory) InitDefault() {
}

func (p *Memory) GetMemoryID() (v string) {
	return p.MemoryID
}

var Memory_UserID_DEFAULT string

func (p *Memory) GetUserID() (v string) {
	if !p.IsSetUserID() {
		return Memory_UserID_DEFAULT
	}
	return *p.UserID
}

var Memory_AvatarID_DEFAULT string

func (p *Memory) GetAvatarID() (v string) {
	if !p.IsSetAvatarID() {
		return Memory_AvatarID_DEFAULT
	}
	return *p.AvatarID
}

func (p *Memory) GetMemoryType() (v MemoryType) {
	return p.MemoryType
}

func (p *Memory) GetMemoryName() (v string) {
	return p.MemoryName
}

func (p *Memory) GetGroup() (v string) {
	return p.Group
}

func (p *Memory) GetSubGroup() (v string) {
	return p.SubGroup
}

func (p *Memory) GetContent() (v string) {
	return p.Content
}

var Memory_ContentVector_DEFAULT []float64

func (p *Memory) GetContentVector() (v []float64) {
	if !p.IsSetContentVector() {
		return Memory_ContentVector_DEFAULT
	}
	return p.ContentVector
}

func (p *Memory) GetCreatedAtUnixMilli() (v int64) {
	return p.CreatedAtUnixMilli
}

func (p *Memory) GetLastUpdatedAtUnixMilli() (v int64) {
	return p.LastUpdatedAtUnixMilli
}

func (p *Memory) GetMemoryDateAtUnixSec() (v int64) {
	return p.MemoryDateAtUnixSec
}

func (p *Memory) GetExt() (v map[string]string) {
	return p.Ext
}

func (p *Memory) IsSetUserID() bool {
	return p.UserID != nil
}

func (p *Memory) IsSetAvatarID() bool {
	return p.AvatarID != nil
}

func (p *Memory) IsSetContentVector() bool {
	return p.ContentVector != nil
}

func (p *Memory) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Memory(%+v)", *p)
}

type MemoryRecallRespData struct {
	Memories []*Memory `thrift:"memories,1" form:"memories" json:"memories" query:"memories"`
}

func NewMemoryRecallRespData() *MemoryRecallRespData {
	return &MemoryRecallRespData{}
}

func (p *MemoryRecallRespData) InitDefault() {
}

func (p *MemoryRecallRespData) GetMemories() (v []*Memory) {
	return p.Memories
}

func (p *MemoryRecallRespData) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryRecallRespData(%+v)", *p)
}

type MemoryRecallResponse struct {
	Memories []*Memory `thrift:"memories,1" form:"memories" json:"memories" query:"memories"`
	BaseResp *base.BaseResp        `thrift:"base_resp,255" form:"base_resp" json:"base_resp" query:"base_resp"`
}

func NewMemoryRecallResponse() *MemoryRecallResponse {
	return &MemoryRecallResponse{}
}

func (p *MemoryRecallResponse) InitDefault() {
}


var MemoryRecallResponse_BaseResp_DEFAULT *base.BaseResp

func (p *MemoryRecallResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return MemoryRecallResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}


func (p *MemoryRecallResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *MemoryRecallResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MemoryRecallResponse(%+v)", *p)
}
