// Code generated by hertz generator.

package main

import (
	"douyin/avatar/serv_template_open/biz"

	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	// todo：业务初始化了逻辑
	biz.Init()

	// 抖音云需要8000端口
	h := server.Default(server.WithStreamBody(true), server.WithHostPorts(":8000"))

	register(h)
	h.Spin()
}
