// Code generated by thriftgo (0.3.17). DO NOT EDIT.

package common

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

type Role int64

const (
	Role__              Role = 0
	Role_Role_System    Role = 1
	Role_Role_User      Role = 2
	Role_Role_Assistant Role = 3
)

func (p Role) String() string {
	switch p {
	case Role__:
		return "_"
	case Role_Role_System:
		return "Role_System"
	case Role_Role_User:
		return "Role_User"
	case Role_Role_Assistant:
		return "Role_Assistant"
	}
	return "<UNSET>"
}

func RoleFromString(s string) (Role, error) {
	switch s {
	case "_":
		return Role__, nil
	case "Role_System":
		return Role_Role_System, nil
	case "Role_User":
		return Role_Role_User, nil
	case "Role_Assistant":
		return Role_Role_Assistant, nil
	}
	return Role(0), fmt.Errorf("not a valid Role string")
}

func RolePtr(v Role) *Role { return &v }
func (p *Role) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = Role(result.Int64)
	return
}

func (p *Role) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type AvatarInfo struct {
	AvatarAppID string `thrift:"avatar_app_id,1" form:"avatar_app_id" json:"avatar_app_id" query:"avatar_app_id"`
}

func NewAvatarInfo() *AvatarInfo {
	return &AvatarInfo{}
}

func (p *AvatarInfo) InitDefault() {
}

func (p *AvatarInfo) GetAvatarAppID() (v string) {
	return p.AvatarAppID
}

func (p *AvatarInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AvatarInfo(%+v)", *p)
}

type UserInfo struct {
	OpenID string  `thrift:"open_id,1" form:"open_id" json:"open_id" query:"open_id"`
	UID    *string `thrift:"uid,2,optional" form:"uid" json:"uid,omitempty" query:"uid"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetOpenID() (v string) {
	return p.OpenID
}

var UserInfo_UID_DEFAULT string

func (p *UserInfo) GetUID() (v string) {
	if !p.IsSetUID() {
		return UserInfo_UID_DEFAULT
	}
	return *p.UID
}

func (p *UserInfo) IsSetUID() bool {
	return p.UID != nil
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

type DeviceInfo struct {
	AppID          int32  `thrift:"app_id,1" form:"app_id" json:"app_id" query:"app_id"`
	AppVersion     int64  `thrift:"app_version,2" form:"app_version" json:"app_version" query:"app_version"`
	DeviceID       int64  `thrift:"device_id,3" form:"device_id" json:"device_id" query:"device_id"`
	DevicePlatform string `thrift:"device_platform,4" form:"device_platform" json:"device_platform" query:"device_platform"`
}

func NewDeviceInfo() *DeviceInfo {
	return &DeviceInfo{}
}

func (p *DeviceInfo) InitDefault() {
}

func (p *DeviceInfo) GetAppID() (v int32) {
	return p.AppID
}

func (p *DeviceInfo) GetAppVersion() (v int64) {
	return p.AppVersion
}

func (p *DeviceInfo) GetDeviceID() (v int64) {
	return p.DeviceID
}

func (p *DeviceInfo) GetDevicePlatform() (v string) {
	return p.DevicePlatform
}

func (p *DeviceInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeviceInfo(%+v)", *p)
}

type TrafficSource struct {
	Source      string `thrift:"source,1" form:"source" json:"source" query:"source"`
	EnterFrom   string `thrift:"enter_from,2" form:"enter_from" json:"enter_from" query:"enter_from"`
	TrafficType string `thrift:"traffic_type,3" form:"traffic_type" json:"traffic_type" query:"traffic_type"`
}

func NewTrafficSource() *TrafficSource {
	return &TrafficSource{}
}

func (p *TrafficSource) InitDefault() {
}

func (p *TrafficSource) GetSource() (v string) {
	return p.Source
}

func (p *TrafficSource) GetEnterFrom() (v string) {
	return p.EnterFrom
}

func (p *TrafficSource) GetTrafficType() (v string) {
	return p.TrafficType
}

func (p *TrafficSource) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TrafficSource(%+v)", *p)
}

type BizContext struct {
	BizID      string  `thrift:"biz_id,1" form:"biz_id" json:"biz_id" query:"biz_id"`
	ProviderID string  `thrift:"provider_id,2" form:"provider_id" json:"provider_id" query:"provider_id"`
	TenantID   *string `thrift:"tenant_id,3,optional" form:"tenant_id" json:"tenant_id,omitempty" query:"tenant_id"`
}

func NewBizContext() *BizContext {
	return &BizContext{}
}

func (p *BizContext) InitDefault() {
}

func (p *BizContext) GetBizID() (v string) {
	return p.BizID
}

func (p *BizContext) GetProviderID() (v string) {
	return p.ProviderID
}

var BizContext_TenantID_DEFAULT string

func (p *BizContext) GetTenantID() (v string) {
	if !p.IsSetTenantID() {
		return BizContext_TenantID_DEFAULT
	}
	return *p.TenantID
}

func (p *BizContext) IsSetTenantID() bool {
	return p.TenantID != nil
}

func (p *BizContext) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("BizContext(%+v)", *p)
}

type TraceInfo struct {
	TraceInfo string `thrift:"trace_info,1" form:"trace_info" json:"trace_info" query:"trace_info"`
}

func NewTraceInfo() *TraceInfo {
	return &TraceInfo{}
}

func (p *TraceInfo) InitDefault() {
}

func (p *TraceInfo) GetTraceInfo() (v string) {
	return p.TraceInfo
}

func (p *TraceInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TraceInfo(%+v)", *p)
}
