// Code generated by thriftgo (0.3.17). DO NOT EDIT.

package common

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
)

// 不同的消息的展示形式由content_type来区分，content值为json之后的string，下文为序列化之前的结构
// 当前段的""
type ContentType int64

const (
	// 纯文本类型
	ContentType_ContentType_TEXT ContentType = 0
	// 原FORMAT空间的format
	ContentType_ContentType_FORMAT ContentType = 1
	// 开平卡片类型
	ContentType_ContentType_CARD ContentType = 2
)

func (p ContentType) String() string {
	switch p {
	case ContentType_ContentType_TEXT:
		return "ContentType_TEXT"
	case ContentType_ContentType_FORMAT:
		return "ContentType_FORMAT"
	case ContentType_ContentType_CARD:
		return "ContentType_CARD"
	}
	return "<UNSET>"
}

func ContentTypeFromString(s string) (ContentType, error) {
	switch s {
	case "ContentType_TEXT":
		return ContentType_ContentType_TEXT, nil
	case "ContentType_FORMAT":
		return ContentType_ContentType_FORMAT, nil
	case "ContentType_CARD":
		return ContentType_ContentType_CARD, nil
	}
	return ContentType(0), fmt.Errorf("not a valid ContentType string")
}

func ContentTypePtr(v ContentType) *ContentType { return &v }
func (p *ContentType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = ContentType(result.Int64)
	return
}

func (p *ContentType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// 当前返回的"段"类型；
type SegType int64

const (
	SegType_SegType_Answer SegType = 0
	// 推荐词
	SegType_SegType_FollowUp SegType = 1
)

func (p SegType) String() string {
	switch p {
	case SegType_SegType_Answer:
		return "SegType_Answer"
	case SegType_SegType_FollowUp:
		return "SegType_FollowUp"
	}
	return "<UNSET>"
}

func SegTypeFromString(s string) (SegType, error) {
	switch s {
	case "SegType_Answer":
		return SegType_SegType_Answer, nil
	case "SegType_FollowUp":
		return SegType_SegType_FollowUp, nil
	}
	return SegType(0), fmt.Errorf("not a valid SegType string")
}

func SegTypePtr(v SegType) *SegType { return &v }
func (p *SegType) Scan(value interface{}) (err error) {
	var result sql.NullInt64
	err = result.Scan(value)
	*p = SegType(result.Int64)
	return
}

func (p *SegType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}
