// Code generated by hertz generator.

package avatar_serv

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatstreamMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _onboardingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _avatarMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _servMw() []app.HandlerFunc {
	// your code...
	return nil
}
