// Code generated by thriftgo (0.3.17). DO NOT EDIT.

package avatar_serv

import (
	"context"
	"douyin/avatar/serv_template_open/biz/model/base"
	"douyin/avatar/serv_template_open/biz/model/common"
	"fmt"
)

type CommonContext struct {
	UserInfo      *common.UserInfo      `thrift:"user_info,1" form:"user_info" json:"user_info" query:"user_info"`
	DeviceInfo    *common.DeviceInfo    `thrift:"device_info,2" form:"device_info" json:"device_info" query:"device_info"`
	AvatarInfo    *common.AvatarInfo    `thrift:"avatar_info,3" form:"avatar_info" json:"avatar_info" query:"avatar_info"`
	TrafficSource *common.TrafficSource `thrift:"traffic_source,4" form:"traffic_source" json:"traffic_source" query:"traffic_source"`
	AbParam       string                `thrift:"ab_param,5" form:"ab_param" json:"ab_param" query:"ab_param"`
}

func NewCommonContext() *CommonContext {
	return &CommonContext{}
}

func (p *CommonContext) InitDefault() {
}

var CommonContext_UserInfo_DEFAULT *common.UserInfo

func (p *CommonContext) GetUserInfo() (v *common.UserInfo) {
	if !p.IsSetUserInfo() {
		return CommonContext_UserInfo_DEFAULT
	}
	return p.UserInfo
}

var CommonContext_DeviceInfo_DEFAULT *common.DeviceInfo

func (p *CommonContext) GetDeviceInfo() (v *common.DeviceInfo) {
	if !p.IsSetDeviceInfo() {
		return CommonContext_DeviceInfo_DEFAULT
	}
	return p.DeviceInfo
}

var CommonContext_AvatarInfo_DEFAULT *common.AvatarInfo

func (p *CommonContext) GetAvatarInfo() (v *common.AvatarInfo) {
	if !p.IsSetAvatarInfo() {
		return CommonContext_AvatarInfo_DEFAULT
	}
	return p.AvatarInfo
}

var CommonContext_TrafficSource_DEFAULT *common.TrafficSource

func (p *CommonContext) GetTrafficSource() (v *common.TrafficSource) {
	if !p.IsSetTrafficSource() {
		return CommonContext_TrafficSource_DEFAULT
	}
	return p.TrafficSource
}

func (p *CommonContext) GetAbParam() (v string) {
	return p.AbParam
}

func (p *CommonContext) IsSetUserInfo() bool {
	return p.UserInfo != nil
}

func (p *CommonContext) IsSetDeviceInfo() bool {
	return p.DeviceInfo != nil
}

func (p *CommonContext) IsSetAvatarInfo() bool {
	return p.AvatarInfo != nil
}

func (p *CommonContext) IsSetTrafficSource() bool {
	return p.TrafficSource != nil
}

func (p *CommonContext) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CommonContext(%+v)", *p)
}

type CopilotContent struct {
	Type      common.ContentType `thrift:"type,1" form:"type" json:"type" query:"type"`
	Content   string             `thrift:"content,2" form:"content" json:"content" query:"content"`
	Role      common.Role        `thrift:"role,3" form:"role" json:"role" query:"role"`
	SegFinish bool               `thrift:"seg_finish,4" form:"seg_finish" json:"seg_finish" query:"seg_finish"`
	SegType   common.SegType     `thrift:"seg_type,5" form:"seg_type" json:"seg_type" query:"seg_type"`
}

func NewCopilotContent() *CopilotContent {
	return &CopilotContent{}
}

func (p *CopilotContent) InitDefault() {
}

func (p *CopilotContent) GetType() (v common.ContentType) {
	return p.Type
}

func (p *CopilotContent) GetContent() (v string) {
	return p.Content
}

func (p *CopilotContent) GetRole() (v common.Role) {
	return p.Role
}

func (p *CopilotContent) GetSegFinish() (v bool) {
	return p.SegFinish
}

func (p *CopilotContent) GetSegType() (v common.SegType) {
	return p.SegType
}

func (p *CopilotContent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CopilotContent(%+v)", *p)
}

type MessageContent struct {
	Type    common.ContentType `thrift:"type,1" form:"type" json:"type" query:"type"`
	Content string             `thrift:"content,2" form:"content" json:"content" query:"content"`
}

func NewMessageContent() *MessageContent {
	return &MessageContent{}
}

func (p *MessageContent) InitDefault() {
}

func (p *MessageContent) GetType() (v common.ContentType) {
	return p.Type
}

func (p *MessageContent) GetContent() (v string) {
	return p.Content
}

func (p *MessageContent) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("MessageContent(%+v)", *p)
}

//	struct ContentMetaInfo {
//	    1: content.MetaType type,
//	    2: string info
//	}
type Message struct {
	ConversationID string          `thrift:"conversation_id,1" form:"conversation_id" json:"conversation_id" query:"conversation_id"`
	SessionID      string          `thrift:"session_id,2" form:"session_id" json:"session_id" query:"session_id"`
	MessageID      string          `thrift:"message_id,3" form:"message_id" json:"message_id" query:"message_id"`
	Role           common.Role     `thrift:"role,4" form:"role" json:"role" query:"role"`
	Content        *MessageContent `thrift:"content,5" form:"content" json:"content" query:"content"`
}

func NewMessage() *Message {
	return &Message{}
}

func (p *Message) InitDefault() {
}

func (p *Message) GetConversationID() (v string) {
	return p.ConversationID
}

func (p *Message) GetSessionID() (v string) {
	return p.SessionID
}

func (p *Message) GetMessageID() (v string) {
	return p.MessageID
}

func (p *Message) GetRole() (v common.Role) {
	return p.Role
}

var Message_Content_DEFAULT *MessageContent

func (p *Message) GetContent() (v *MessageContent) {
	if !p.IsSetContent() {
		return Message_Content_DEFAULT
	}
	return p.Content
}

func (p *Message) IsSetContent() bool {
	return p.Content != nil
}

func (p *Message) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Message(%+v)", *p)
}

type ChatContext struct {
	MessageContext []*Message `thrift:"message_context,1" form:"message_context" json:"message_context" query:"message_context"`
}

func NewChatContext() *ChatContext {
	return &ChatContext{}
}

func (p *ChatContext) InitDefault() {
}

func (p *ChatContext) GetMessageContext() (v []*Message) {
	return p.MessageContext
}

func (p *ChatContext) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatContext(%+v)", *p)
}

type ChatStreamRequest struct {
	Message        *Message           `thrift:"message,1" form:"message" json:"message" query:"message"`
	ChatContext    *ChatContext       `thrift:"chat_context,2" form:"chat_context" json:"chat_context" query:"chat_context"`
	ReplyMessageID string             `thrift:"reply_message_id,3" form:"reply_message_id" json:"reply_message_id" query:"reply_message_id"`
	BizContext     *common.BizContext `thrift:"biz_context,4" form:"biz_context" json:"biz_context" query:"biz_context"`
	CommonContext  *CommonContext     `thrift:"common_context,254" form:"common_context" json:"common_context" query:"common_context"`
	Base           *base.Base         `thrift:"base,255" form:"base" json:"base" query:"base"`
}

func NewChatStreamRequest() *ChatStreamRequest {
	return &ChatStreamRequest{}
}

func (p *ChatStreamRequest) InitDefault() {
}

var ChatStreamRequest_Message_DEFAULT *Message

func (p *ChatStreamRequest) GetMessage() (v *Message) {
	if !p.IsSetMessage() {
		return ChatStreamRequest_Message_DEFAULT
	}
	return p.Message
}

var ChatStreamRequest_ChatContext_DEFAULT *ChatContext

func (p *ChatStreamRequest) GetChatContext() (v *ChatContext) {
	if !p.IsSetChatContext() {
		return ChatStreamRequest_ChatContext_DEFAULT
	}
	return p.ChatContext
}

func (p *ChatStreamRequest) GetReplyMessageID() (v string) {
	return p.ReplyMessageID
}

var ChatStreamRequest_BizContext_DEFAULT *common.BizContext

func (p *ChatStreamRequest) GetBizContext() (v *common.BizContext) {
	if !p.IsSetBizContext() {
		return ChatStreamRequest_BizContext_DEFAULT
	}
	return p.BizContext
}

var ChatStreamRequest_CommonContext_DEFAULT *CommonContext

func (p *ChatStreamRequest) GetCommonContext() (v *CommonContext) {
	if !p.IsSetCommonContext() {
		return ChatStreamRequest_CommonContext_DEFAULT
	}
	return p.CommonContext
}

var ChatStreamRequest_Base_DEFAULT *base.Base

func (p *ChatStreamRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ChatStreamRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *ChatStreamRequest) IsSetMessage() bool {
	return p.Message != nil
}

func (p *ChatStreamRequest) IsSetChatContext() bool {
	return p.ChatContext != nil
}

func (p *ChatStreamRequest) IsSetBizContext() bool {
	return p.BizContext != nil
}

func (p *ChatStreamRequest) IsSetCommonContext() bool {
	return p.CommonContext != nil
}

func (p *ChatStreamRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ChatStreamRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatStreamRequest(%+v)", *p)
}

type ChatStreamResponse struct {
	StreamFinish bool              `thrift:"stream_finish,1" form:"stream_finish" json:"stream_finish" query:"stream_finish"`
	Content      *CopilotContent   `thrift:"content,2" form:"content" json:"content" query:"content"`
	TraceInfo    *common.TraceInfo `thrift:"trace_info,254" form:"trace_info" json:"trace_info" query:"trace_info"`
	BaseResp     *base.BaseResp    `thrift:"base_resp,255" form:"-" json:"-" query:"-"`
}

func NewChatStreamResponse() *ChatStreamResponse {
	return &ChatStreamResponse{}
}

func (p *ChatStreamResponse) InitDefault() {
}

func (p *ChatStreamResponse) GetStreamFinish() (v bool) {
	return p.StreamFinish
}

var ChatStreamResponse_Content_DEFAULT *CopilotContent

func (p *ChatStreamResponse) GetContent() (v *CopilotContent) {
	if !p.IsSetContent() {
		return ChatStreamResponse_Content_DEFAULT
	}
	return p.Content
}

var ChatStreamResponse_TraceInfo_DEFAULT *common.TraceInfo

func (p *ChatStreamResponse) GetTraceInfo() (v *common.TraceInfo) {
	if !p.IsSetTraceInfo() {
		return ChatStreamResponse_TraceInfo_DEFAULT
	}
	return p.TraceInfo
}

var ChatStreamResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ChatStreamResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ChatStreamResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ChatStreamResponse) IsSetContent() bool {
	return p.Content != nil
}

func (p *ChatStreamResponse) IsSetTraceInfo() bool {
	return p.TraceInfo != nil
}

func (p *ChatStreamResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ChatStreamResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatStreamResponse(%+v)", *p)
}

type OnBoardingRequest struct {
	Message        *Message           `thrift:"message,1" form:"message" json:"message" query:"message"`
	ChatContext    *ChatContext       `thrift:"chat_context,2" form:"chat_context" json:"chat_context" query:"chat_context"`
	ReplyMessageID string             `thrift:"reply_message_id,3" form:"reply_message_id" json:"reply_message_id" query:"reply_message_id"`
	BizContext     *common.BizContext `thrift:"biz_context,4" form:"biz_context" json:"biz_context" query:"biz_context"`
	CommonContext  *CommonContext     `thrift:"common_context,254" form:"common_context" json:"common_context" query:"common_context"`
	Base           *base.Base         `thrift:"base,255" form:"base" json:"base" query:"base"`
}

func NewOnBoardingRequest() *OnBoardingRequest {
	return &OnBoardingRequest{}
}

func (p *OnBoardingRequest) InitDefault() {
}

var OnBoardingRequest_Message_DEFAULT *Message

func (p *OnBoardingRequest) GetMessage() (v *Message) {
	if !p.IsSetMessage() {
		return OnBoardingRequest_Message_DEFAULT
	}
	return p.Message
}

var OnBoardingRequest_ChatContext_DEFAULT *ChatContext

func (p *OnBoardingRequest) GetChatContext() (v *ChatContext) {
	if !p.IsSetChatContext() {
		return OnBoardingRequest_ChatContext_DEFAULT
	}
	return p.ChatContext
}

func (p *OnBoardingRequest) GetReplyMessageID() (v string) {
	return p.ReplyMessageID
}

var OnBoardingRequest_BizContext_DEFAULT *common.BizContext

func (p *OnBoardingRequest) GetBizContext() (v *common.BizContext) {
	if !p.IsSetBizContext() {
		return OnBoardingRequest_BizContext_DEFAULT
	}
	return p.BizContext
}

var OnBoardingRequest_CommonContext_DEFAULT *CommonContext

func (p *OnBoardingRequest) GetCommonContext() (v *CommonContext) {
	if !p.IsSetCommonContext() {
		return OnBoardingRequest_CommonContext_DEFAULT
	}
	return p.CommonContext
}

var OnBoardingRequest_Base_DEFAULT *base.Base

func (p *OnBoardingRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return OnBoardingRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *OnBoardingRequest) IsSetMessage() bool {
	return p.Message != nil
}

func (p *OnBoardingRequest) IsSetChatContext() bool {
	return p.ChatContext != nil
}

func (p *OnBoardingRequest) IsSetBizContext() bool {
	return p.BizContext != nil
}

func (p *OnBoardingRequest) IsSetCommonContext() bool {
	return p.CommonContext != nil
}

func (p *OnBoardingRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *OnBoardingRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OnBoardingRequest(%+v)", *p)
}

type OnBoardingResponse struct {
	StreamFinish bool              `thrift:"stream_finish,1" form:"stream_finish" json:"stream_finish" query:"stream_finish"`
	Content      *CopilotContent   `thrift:"content,2" form:"content" json:"content" query:"content"`
	TraceInfo    *common.TraceInfo `thrift:"trace_info,254" form:"trace_info" json:"trace_info" query:"trace_info"`
	BaseResp     *base.BaseResp    `thrift:"base_resp,255" form:"-" json:"-" query:"-"`
}

func NewOnBoardingResponse() *OnBoardingResponse {
	return &OnBoardingResponse{}
}

func (p *OnBoardingResponse) InitDefault() {
}

func (p *OnBoardingResponse) GetStreamFinish() (v bool) {
	return p.StreamFinish
}

var OnBoardingResponse_Content_DEFAULT *CopilotContent

func (p *OnBoardingResponse) GetContent() (v *CopilotContent) {
	if !p.IsSetContent() {
		return OnBoardingResponse_Content_DEFAULT
	}
	return p.Content
}

var OnBoardingResponse_TraceInfo_DEFAULT *common.TraceInfo

func (p *OnBoardingResponse) GetTraceInfo() (v *common.TraceInfo) {
	if !p.IsSetTraceInfo() {
		return OnBoardingResponse_TraceInfo_DEFAULT
	}
	return p.TraceInfo
}

var OnBoardingResponse_BaseResp_DEFAULT *base.BaseResp

func (p *OnBoardingResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return OnBoardingResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *OnBoardingResponse) IsSetContent() bool {
	return p.Content != nil
}

func (p *OnBoardingResponse) IsSetTraceInfo() bool {
	return p.TraceInfo != nil
}

func (p *OnBoardingResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *OnBoardingResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("OnBoardingResponse(%+v)", *p)
}

type ChatRequest struct {
	Message        *Message           `thrift:"message,1" form:"message" json:"message" query:"message"`
	ChatContext    *ChatContext       `thrift:"chat_context,2" form:"chat_context" json:"chat_context" query:"chat_context"`
	ReplyMessageID string             `thrift:"reply_message_id,3" form:"reply_message_id" json:"reply_message_id" query:"reply_message_id"`
	BizContext     *common.BizContext `thrift:"biz_context,4" form:"biz_context" json:"biz_context" query:"biz_context"`
	CommonContext  *CommonContext     `thrift:"common_context,254" form:"common_context" json:"common_context" query:"common_context"`
	Base           *base.Base         `thrift:"base,255" form:"base" json:"base" query:"base"`
}

func NewChatRequest() *ChatRequest {
	return &ChatRequest{}
}

func (p *ChatRequest) InitDefault() {
}

var ChatRequest_Message_DEFAULT *Message

func (p *ChatRequest) GetMessage() (v *Message) {
	if !p.IsSetMessage() {
		return ChatRequest_Message_DEFAULT
	}
	return p.Message
}

var ChatRequest_ChatContext_DEFAULT *ChatContext

func (p *ChatRequest) GetChatContext() (v *ChatContext) {
	if !p.IsSetChatContext() {
		return ChatRequest_ChatContext_DEFAULT
	}
	return p.ChatContext
}

func (p *ChatRequest) GetReplyMessageID() (v string) {
	return p.ReplyMessageID
}

var ChatRequest_BizContext_DEFAULT *common.BizContext

func (p *ChatRequest) GetBizContext() (v *common.BizContext) {
	if !p.IsSetBizContext() {
		return ChatRequest_BizContext_DEFAULT
	}
	return p.BizContext
}

var ChatRequest_CommonContext_DEFAULT *CommonContext

func (p *ChatRequest) GetCommonContext() (v *CommonContext) {
	if !p.IsSetCommonContext() {
		return ChatRequest_CommonContext_DEFAULT
	}
	return p.CommonContext
}

var ChatRequest_Base_DEFAULT *base.Base

func (p *ChatRequest) GetBase() (v *base.Base) {
	if !p.IsSetBase() {
		return ChatRequest_Base_DEFAULT
	}
	return p.Base
}

func (p *ChatRequest) IsSetMessage() bool {
	return p.Message != nil
}

func (p *ChatRequest) IsSetChatContext() bool {
	return p.ChatContext != nil
}

func (p *ChatRequest) IsSetBizContext() bool {
	return p.BizContext != nil
}

func (p *ChatRequest) IsSetCommonContext() bool {
	return p.CommonContext != nil
}

func (p *ChatRequest) IsSetBase() bool {
	return p.Base != nil
}

func (p *ChatRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatRequest(%+v)", *p)
}

type ChatResponse struct {
	Content   []*CopilotContent `thrift:"content,1" form:"content" json:"content" query:"content"`
	TraceInfo *common.TraceInfo `thrift:"trace_info,254" form:"trace_info" json:"trace_info" query:"trace_info"`
	BaseResp  *base.BaseResp    `thrift:"base_resp,255" form:"-" json:"-" query:"-"`
}

func NewChatResponse() *ChatResponse {
	return &ChatResponse{}
}

func (p *ChatResponse) InitDefault() {
}

func (p *ChatResponse) GetContent() (v []*CopilotContent) {
	return p.Content
}

var ChatResponse_TraceInfo_DEFAULT *common.TraceInfo

func (p *ChatResponse) GetTraceInfo() (v *common.TraceInfo) {
	if !p.IsSetTraceInfo() {
		return ChatResponse_TraceInfo_DEFAULT
	}
	return p.TraceInfo
}

var ChatResponse_BaseResp_DEFAULT *base.BaseResp

func (p *ChatResponse) GetBaseResp() (v *base.BaseResp) {
	if !p.IsSetBaseResp() {
		return ChatResponse_BaseResp_DEFAULT
	}
	return p.BaseResp
}

func (p *ChatResponse) IsSetTraceInfo() bool {
	return p.TraceInfo != nil
}

func (p *ChatResponse) IsSetBaseResp() bool {
	return p.BaseResp != nil
}

func (p *ChatResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ChatResponse(%+v)", *p)
}

type AvatarService interface {
	// 开场白
	OnBoarding(ctx context.Context, req *OnBoardingRequest) (r *OnBoardingResponse, err error)
	// 会话部分
	ChatStream(ctx context.Context, req *ChatStreamRequest) (r *ChatStreamResponse, err error)
	// 非流式对话，主要服务于一些评测/debug 场景
	Chat(ctx context.Context, req *ChatRequest) (r *ChatResponse, err error)
}
