// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	avatar_serv "douyin/avatar/serv_template_open/biz/router/avatar_serv"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	avatar_serv.Register(r)
}
